#!/usr/bin/env node
const Mustache = require('mustache') 
const fs = require('fs');
const { execSync } = require('child_process');
const canPush = process.argv.indexOf('--push') > -1
var images= JSON.parse(fs.readFileSync('images.json', 'utf8'))
var dockerFiletemplate = fs.readFileSync('Dockerfile', 'utf8')
images.forEach(imageInfo => { 
    var output = Mustache.render(dockerFiletemplate, imageInfo);
    var tag = `${imageInfo.envoy}-${imageInfo.tomcat}-alpine`
    var dockerfileName = `Dockerfile-${tag}`
    fs.writeFileSync(dockerfileName,output)
    console.log(`building image for tomcat ${imageInfo.tomcat} and envoy ${imageInfo.envoy} `)  
    let stdout = execSync(`docker build -t envoyproxyplus/envoy-tomcat:${tag} -f ${dockerfileName} .`)
    console.log(stdout.toString())
    if(canPush)
    {
        stdout = execSync(`docker push envoyproxyplus/envoy-tomcat:${tag}`)
        console.log(stdout.toString())    
    }
});